flags: {}
packages:
  - '.'
  - '../ecstasy'
  - '../sequoia'
  - '../jps'
  - extra-dep: true
    location:
      git: https://github.com/isovector/htiled.git
      commit: bb18e7dd85b3f1fe8f9e339f8e6b8ea942bbe361
  - extra-dep: true
    location:
      git: https://github.com/schell/aeson-tiled.git
      commit: 32fa27eb3313723062cbc771539c101ad3e5f0af

extra-deps:
  - sdl2-2.3.0
  - frpnow-0.18
  - recursion-schemes-5.0.2
  - astar-0.3.0.0
  - aeson-1.2.2.0
  - th-abstraction-0.2.6.0
  - transformers-0.5.5.0

resolver: lts-11.9
